language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-railsbox' ]; then cd .. && eval "mv $currentfolder generator-railsbox" && cd generator-railsbox; fi

