#!/usr/bin/env ruby

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'sqlite'
cookbook 'mysql'
cookbook 'git'
cookbook 'postgresql'
cookbook 'database', :git => 'git://github.com/manuelvanrijn/cookbook-database.git', :ref => 'grant-roles'
cookbook 'build-essential', '~> 1.4.4'
cookbook 'nodejs', :git => 'https://github.com/mdxp/nodejs-cookbook.git'
cookbook 'ruby_build'
cookbook 'rbenv', :git => 'https://github.com/fnichol/chef-rbenv', :ref => 'v0.7.2'
cookbook 'vim'
